### ISSUE TITLE
Can not add bot to conversation

### ISSUE THREAD

**Issue by M3NIX** [wireapp/echo-bot#45] opened 2019-08-27 06:48 UTC
Right now I am trying to deploy the echo bot and got quite some part working.
I am now stuck at the part where I am trying to add the bot to a conversation. Therefore I am using the add.sh script.

But I am always getting this response:
```
HTTP/1.1 502 Bad Gateway
Access-Control-Expose-Headers: Request-Id, Location
Content-Type: application/json
Date: Tue, 27 Aug 2019 06:28:09 GMT
Request-Id: 76455ec1809c3fb4b25cec4cbd72d238
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Content-Length: 155
Connection: keep-alive

{"code":502,"message":"{\"code\":502,\"message\":\"The upstream service returned an invalid response.\",\"label\":\"bad-gateway\"}","label":"server-error"}
Done!
```

The problem is I can not even see the request in the logs of the bot.
My own requests (with curl) instead are showing up.

```
$ curl https://bot.ortel.tech/bots/status  
**All good!**
```
```
[27/Aug/2019:06:27:54 +0000] "GET /bots/status HTTP/1.1" 200 13 "-" "curl/7.65.3" 5
```

Some more infos which might help finding the problem:
```
$ ./myprovider.sh list-services
[
  {
    "summary": "summary",
    "public_keys": [
      {
        "size": 4096,
        "pem": "-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvOZ7OnydDAL0xLd8BB4O\nk12No0/txpfvdrGgzmlFmuJztGzbkviRGecLf3NIMYmc4EMsX22Mo8aZOvwgHduX\nYYgPWjRJzUbCa0tIibjKoWho0pIwn8JK0+VJ3DPO1uPb86nTBnvfO3aM70DuHAgz\nPFeCZMBdMMuZ6l14+vmVsdhEiky+v5m+/MCEC6bUSJ0j1p/Xb1B1/kztoacpXd60\nxk5dhbHgG8rdw0Y2OHGMRr5VW2t7NN1QcqSGgZhdphkmC0QUXXbTWKbiBdSfqVLp\n5yy8Ngx/Jzx5x3Cr6N9GpgRQ+ys1y5WcuWrTpgSytOj9f3ljGQXUUiyo0bkNusWl\nfFjeaLgx0CbhivzoEiZP+mnk597Qkpd832xLezXZkknSxfkb6IXe+hTxfogTTn08\nQVK+WQIpA3OtGyHRRnkjlDW8S5PjkQ6Ij+gHGD+2A7Ie2ISS86u1DwcssPfaUnqa\nmCOn2dHAxJjLQsy/zoLX7WC2ZWvuuxnEJ1Cc1h65bgnuOpYNIomQ9lwzScWKJrNh\n3qeXjcpDeDa07jxn3pukaC0AABmhzt7xS5Vo6Acxu0I5wAxbPH4QUx1nHoYl7Fks\nlgS3zFuBp/dWs4DBKPBhgmzWvoQi9+N/kWeshcbmTdHyAy1n5HtUEL5LQglapv3P\n0DKIkF3dvTDNIErrW4THnsMCAwEAAQ==\n-----END PUBLIC KEY-----\n",
        "type": "rsa"
      }
    ],
    "enabled": true,
    "base_url": "https://bot.ortel.tech:443", #tried https://bot.ortel.tech aswell
    "name": "M3NIX Echo Bot",
    "auth_tokens": [
      "MY SECRET AUTH KEY"
    ],
    "id": "831040d5-66bc-45a4-a634-54947b68b034",
    "assets": [],
    "description": "My try to deploy a working wire bot",
    "tags": [
      "tutorial"
    ]
  }
```

```
$ cat echo.yaml
server:
  # root path. Remove it if you dont need it
  rootPath: /

# comment out these 2 lines in order to enable HTTP reqs logging
#  requestLog:
#    appenders: []

# Log lever: INFO | DEBUG | ERROR
logging:
  level: INFO
  loggers:
    "com.wire.bots.logger": INFO

auth: MY SECRET AUTH KEY   # Service's auth token

# Swagger documentation... useful sometimes
swagger:
  resourcePackage: com.wire.bots.sdk.server.resources
  uriPrefix: /echo
  schemes:
    - http
    - https

# Calling stuff (optional)
module: echo
portMin: 32768
portMax: 32867
ingress: localhost

#redis DB. Primary keys are stored here
db:
  host: localhost
  driver: redis
  port: 6379    #redis default port
  password:

# To use file system as the storage use these settings
#db:
#  driver: fs
```

**Comment by dkovacevic** [comment] 2019-08-27 09:41
Try setting `baseURL` for your service as: `https://bot.ortel.tech/bots`

**Comment by dkovacevic** [comment] 2019-08-27 09:50
Just noticed there are many errors regarding TLS cert for this service. Can you verify that the publickey.pem is correct

**Comment by M3NIX** [comment] 2019-08-27 10:17
> Try setting `baseURL` for your service as: `https://bot.ortel.tech/bots`
Did so. Nothing changed. Same error. No request in the logs of the bot.

> Just noticed there are many errors regarding TLS cert for this service. Can you verify that the publickey.pem is correct

I generated the public key with following command:
``` 
$ echo -n | openssl s_client -connect bot.ortel.tech:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | openssl x509 -pubkey -noout -in - > publickey.pem
```
which results in following file:
```
$ cat publickey.pem 
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvOZ7OnydDAL0xLd8BB4O
k12No0/txpfvdrGgzmlFmuJztGzbkviRGecLf3NIMYmc4EMsX22Mo8aZOvwgHduX
YYgPWjRJzUbCa0tIibjKoWho0pIwn8JK0+VJ3DPO1uPb86nTBnvfO3aM70DuHAgz
PFeCZMBdMMuZ6l14+vmVsdhEiky+v5m+/MCEC6bUSJ0j1p/Xb1B1/kztoacpXd60
xk5dhbHgG8rdw0Y2OHGMRr5VW2t7NN1QcqSGgZhdphkmC0QUXXbTWKbiBdSfqVLp
5yy8Ngx/Jzx5x3Cr6N9GpgRQ+ys1y5WcuWrTpgSytOj9f3ljGQXUUiyo0bkNusWl
fFjeaLgx0CbhivzoEiZP+mnk597Qkpd832xLezXZkknSxfkb6IXe+hTxfogTTn08
QVK+WQIpA3OtGyHRRnkjlDW8S5PjkQ6Ij+gHGD+2A7Ie2ISS86u1DwcssPfaUnqa
mCOn2dHAxJjLQsy/zoLX7WC2ZWvuuxnEJ1Cc1h65bgnuOpYNIomQ9lwzScWKJrNh
3qeXjcpDeDa07jxn3pukaC0AABmhzt7xS5Vo6Acxu0I5wAxbPH4QUx1nHoYl7Fks
lgS3zFuBp/dWs4DBKPBhgmzWvoQi9+N/kWeshcbmTdHyAy1n5HtUEL5LQglapv3P
0DKIkF3dvTDNIErrW4THnsMCAwEAAQ==
-----END PUBLIC KEY-----
```
this matches the publickey I posted above.
What kind of TLS cert errors are you noticing?

**Comment by M3NIX** [comment] 2019-09-03 15:03
I was able to find the problem. 
In my setup I have the echo bot running in a docker container which is sitting behind the traefik reverse proxy. The reverse proxy is serving the SSL Certificate for https://bot.ortel.tech. 
On another (older) machine I was requesting the public key of the certificate and noticed that I got another one compared to the one I posted here and on my main computer. I investigated this more and found out that the reverse proxy needs the Server Name Indication (SNI) extension for the TLS handshake otherwise it is serving the default traefik certificate [more information here](https://github.com/containous/traefik/issues/2829). 
I could confirm it by issuing the following commands:
```
$ openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017

$ echo | openssl s_client -servername bot.ortel.tech -connect 'bot.ortel.tech:443' 2>/dev/null | grep 'issuer'
issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3

$ echo | openssl s_client -connect 'bot.ortel.tech:443' 2>/dev/null | grep 'issuer'
issuer=/CN=TRAEFIK DEFAULT CERT
```
 
After I set the publickey in the Wire Backend to the TRAEFIK DEFAULT CERT public key everything was fine and the Wire Backend could send requests to my bot.
Therefore I could confirm that the servername attribute is missing in the request from the Wire Backend.

Is it possible to add SNI/servername to the requests coming from the Wire Backend since it is a feature which could help to improve the code in general?

**Comment by tiago-loureiro** [comment] 2019-09-05 13:00
Hi @M3NIX 
Thank you for the detailed report! It helps us a lot in debugging, we have a good idea of what the root cause is now and how we can test/fix it!

> In my bot server logs I could see that the Wire Backend is sending the requests with an go application (Go-http-client/1.1).

Are you sure about this? Because our Backend is fully written in Haskell.

**Comment by M3NIX** [comment] 2019-09-05 13:05
> Are you sure about this? Because our Backend is fully written in Haskell.
Okay forget that about go... The reverse proxy is written in go and therefore in the logs of the bot the user agent is showing up as Go...
But that does not change something about the problem :)

**Comment by M3NIX** [comment] 2019-10-02 10:40
@tiago-loureiro Should I create an issue on the wire-server repo so this will not get forgotten or are you already tracing that problem internally?

**Comment by tiago-loureiro** [comment] 2019-10-08 12:05
Hi @M3NIX 

Thanks for following up on this, we're tracking it internally already. Will let you know as we have an update for you.

**Comment by arianvp** [comment] 2019-10-15 09:38
@M3NIX I have confirmed that we indeed do not do SNI currently.  I'll be working on a patch for this. It involves bumping the version of the haskell client library that we use.

**Comment by arianvp** [comment] 2019-11-05 08:41
Hey @M3NIX there's a pending PR that will hopefully resolve this issue which will be merged soon https://github.com/wireapp/wire-server/pull/899

I'll nudge you once we've rolled it out to production!

**Comment by jmatsushita** [comment] 2019-11-20 11:53
Hi there,

I just bumped into the same issue trying to deploy `echo-bot` as well. Slightly different reverse proxy infrastructure (I'm using Rancher and the K8s nginx ingress) but the symptoms are the same, i.e. requesting the public key gets a default cert if the server name isn't added.

I see the PR you linked to has been merged. Any update on the roll out to production?

**Comment by tiago-loureiro** [comment] 2019-11-20 13:04
Hi @jmatsushita we should roll this out to production this week, we'll update this issue as soon as we do.

**Comment by arianvp** [comment] 2019-11-28 14:03
Apparently at the time @tiago-loureiro commented the fix was already rolled out to production. So apparently addying SNI support did not fix this issue. So this will require some more investigation on our side.  I'll try deploying echo-bot behind a reverse-proxy to reproduce this again locally.

**Comment by jmatsushita** [comment] 2019-12-01 13:14
All working for me now. Thanks!

**Comment by orandev** [comment] 2020-04-30 09:14
Hello,
I have an issue on my platform related to this.
brig chart version is 0.100.0
I cannot add a bot to a conversation.
I have configured the proxy env vars inside brig pods because they need to go through a proxy to get access to the bot URL.
Let's say proxy host is "proxy_host.example.com".

If I do a curl https://bot_host.example.com from brig pod, the request goes through the proxy:
HTTP CONNECT bot_host.example.com:443
Then I see this in the TLS ClientHello:
ServerName: bot_host.example.com

But when I try adding the bot to a conversation, brig connects to the proxy:
HTTP CONNECT bot_host.example.com:443
then sends this in the TLS ClientHello:
ServerName: proxy_host.example.com

And thus don't get the correct certificate.
SNI in the request sent from brig should contain the host of the bot url, not the host of the proxy.

Could you look into this please?

**Comment by arianvp** [comment] 2020-05-07 12:54
Could you tell me a bit more about the proxy setup?

I want to make sure that it's not the proxy that is stripping SNI in some way.

**Comment by orandev** [comment] 2020-05-07 14:24
I don't understand, it's the brig client that is sending the wrong SNI, how is the proxy involved?

**Comment by arianvp** [comment] 2020-05-07 15:11
Thanks; i'll see if I can reproduce this locally.  chart `0.100.0` is new enough that it should have had the SNI fix included... I'll investigate

**Comment by arianvp** [comment] 2020-05-07 16:26
@orandev I found the issue. Great find by the way.

The `http-client` that we use has a bug on this line:

https://github.com/snoyberg/http-client/blob/master/http-client-openssl/Network/HTTP/Client/OpenSSL.hs#L75

it sets the `SNI` name to the proxy `hostname` instead of to `serverName` . Which is wrong.

So when `https_proxy` is set; then the SNI name is replaced with the Proxy's hostname instead of the server name that you're trying to reach. This seems in line with the behaviour that you are reporting

I will fix this in our fork and make a new release of `brig`.  and I will also make a pull request to the upstream project

**Closed** 2020-05-26 10:30 UTC

**Comment by arianvp** [comment] 2020-06-17 16:03
@orandev a fix is under way in https://github.com/wireapp/wire-server/pull/1138
